version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: fitai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fitai
    volumes:
      - mongo_data:/data/db

  server:
    build: .
    container_name: fitai-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/fitai?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app/server
      - /app/node_modules

volumes:
  mongo_data: